namespace VposApi.Helpers
{
    public static class ResponseReasonCodeDef
    {
        public static readonly Dictionary<string, string> ResponseReasonCodeList = new Dictionary<string, string>
{
    {"1EMBDTNS", "Limit Asim Hatasi"},
    {"ACCINFINV", "Hesap Bilgileri Geçersiz"},
    {"ADVDTNF", "Advice Data bulunamadi."},
    {"AGREFTVMNF", "Tohum Kart ekstre ayi bulunamadi."},
    {"AGRPRFNF", "Tohum Kart profili bulunamadi."},
    {"ALOCBUFERR", "Can not allocate buffer."},
    {"AMNTBIG", "Islem tutari, limiti asmaktadir."},
    {"AMNTNM", "Tutar eslesmemektedir."},
    {"AMTINV", "Geçersiz Tutar"},
    {"AMTNEG", "Negatif Tutarli Islem"},
    {"ARQCF", "ARQC Dogrulama Hatasi"},
    {"ASETLBNONF", "Acquiring terminal settle batch bulunamadi."},
    {"ATCDFF", "İzin Verilen Maksimum Atc Farkı Aşıldı"},
    {"ATMWPBNA", "PIN siz ATM Islemi"},
    {"AUTHMTCH", "Islem hesaba gecmis."},
    {"AUTHNONM", "Otorizasyon numarasi eslesmemektedir."},
    {"BALINQNA", "Limit sorgulama islemine izin verilmemektedir."},
    {"BATCHCLOSE", "Batch is closed. BatchNumber : {0}"},
    {"BICC", "ICC Data Hatasi"},
    {"BICCPLTMS", "ICC Data PlatformID Hatasi"},
    {"BICCPSNMS", "ICC Data PSN Hatasi"},
    {"BINATMINV", "ATM için geçersiz."},
    {"BINBRINV", "Sube için geçersiz."},
    {"BINDMNF", "Yerel BIN bulunamadi."},
    {"BININV", "Geçersiz BIN"},
    {"BINKPRFNF", "BIN Key profil detayi bulunamadi."},
    {"BINMCNF", "Mastercard BIN bulunamadi."},
    {"BINMENTINV", "Manuel giris için geçersiz."},
    {"BINPOSINV", "POS için geçersiz."},
    {"BINVISNF", "Visa BIN bulunamadi."},
    {"BKMUIDINV", "Hatali BKM ID"},
    {"BNKSRVERR", "Bankacılık servis hatası"},
    {"BNSAMNTNM", "Ödül tutari eslesmedi."},
    {"BNSINQNONA", "Puan sorgulama islemine izin verilmedi."},
    {"BNSINQONNA", "Puan sorgulama islemine izin verilmedi."},
    {"BNSTXNNA", "Puan islemine izin verilmedi."},
    {"BS005-60", "Günlük Temssiz islem limiti dolu"},
    {"BTNOINV", "Geçersiz Batch No"},
    {"BTNOMSTINV", "Geçersiz Batch No"},
    {"BTXNNBCRD", "Ödül özelligi olmayan kart ile ödül islem denemesi yapildi."},
    {"BTXNNBTERM", "Ödül özelligi olmayan terminalde ödül islem denemesi yapildi."},
    {"BUSCRDTXNA", "Business asil kart için isleme izin verilmedi."},
    {"CADVCOMCNA", "Tüzel kartlara nakit avans izni verilmemektedir."},
    {"CARSTRCTD", "Kart, isleme kisitlidir."},
    {"CAVV64INV", "invalid base64 encoded cavv data: {0}"},
    {"CAVVFA", "CAVV reddedildi."},
    {"CAVVSVCERR", "Geçersiz CAVV Data: svcCode hatali."},
    {"CAVVUPNERR", "Geçersiz CAVV Data: Geçerlilik tarihi hatali."},
    {"CAVVVRSMM", "CAVV Data Version Missmatch"},
    {"CCOMPERR", "Çip completion çagrilirken hata alindi."},
    {"CCOMPFA", "Chip completion yapilamadi."},
    {"CCOMPTXNNF", "Orijinal islem bulunamadi."},
    {"CCTRNSRVER", "Kredi Karti Islem Hizmet Hatasi"},
    {"CCTXNCCNA", "Nakit islemlere izin verilmemektedir."},
    {"CHIPENTNA", "Chip entry islemine izin verilmedi."},
    {"CHQCRDERR", "Provizyon Hatasi"},
    {"CHQDTINV", "Geçersiz Tarih"},
    {"CLMTAMTEXC", "Nakit limiti yetersiz"},
    {"CLMTSMRYNF", "MainCardLimitSummary Bulunamadi"},
    {"CLNA", "Temassiz isleme izin verilmedi."},
    {"CLRDRDVCNF", "Temassiz okuyucu terminal numarasi bulunamadi."},
    {"CLRDSTDMSM", "Arayan ve Hedef Dominleri ayni"},
    {"CLSDCIRC", "Kapali devre kartlar, diger kart semalarinda islem yapamaz."},
    {"CLSRESTRN", "Temassız işlem kısıtlaması"},
    {"CNLBYBR", "Sube tarafindan iptal edilen kart"},
    {"CNLBYCUS", "Müsteri tarafindan iptal edilen kart"},
    {"CNLCRD", "Iptal Edilen Kart"},
    {"COFSINV", "Credential-on-file Sale İşlemi Yapılamaz"},
    {"CONCVMAMNT", "Islem tutari, ürünün toplam temassiz limitini asiyor"},
    {"CONCVMCNT", "Toplam Temassiz islem sayisi, ürünün sinirini asti"},
    {"CRDAGRNT", "Kart, Tohum Kart degildir."},
    {"CRDDATANF", "Kart verisi bulunamadi."},
    {"CRDDLQERR", "Gecikmedeki Kart"},
    {"CRDDLYDLQ", "Günlük Gecikmedeki Kart"},
    {"CRDEXP", "Vadesi Geçmis Kart"},
    {"CRDFLWST", "Card in followup status error!"},
    {"CRDLMTNF", "Kart Limiti, CardLimit tablosunda bulunamadi."},
    {"CRDLMTUSNF", "Kart riski, CardLimitUsed tablosunda bulunamadi."},
    {"CRDMAFINNF", "Kart, CardMasterFinancial tablosunda bulunamadi."},
    {"CRDMANF", "Kart, CardMaster tablosunda bulunamadi."},
    {"CRDMFHNF", "Card Master Financial kaydı bulunamadı."},
    {"CRDNF", "Kart bilgisi bulunamadi."},
    {"CRDNOINV", "Geçersiz Kart Numarasi"},
    {"CRDNOLEINV", "Geçersiz Kart Numarasi Uzunlugu"},
    {"CRDNOTRKMM", "Track data eslesmedi."},
    {"CRDNUMMS", "Kart Numarasi Hatasi"},
    {"CRDPERDLQ", "Periyodik Gecikmedeki Kart"},
    {"CRDRESTRN", "Kart, isleme kisitlidir."},
    {"CRDRSTERR", "Kart, isleme kisitlidir."},
    {"CRDRWNF", "Hediye Karti bulunamadi."},
    {"CRDSTINV", "Pasif Kart"},
    {"CRDSTPIN", "Pin Yüklenmemis Kart. Önce Pin Yükleyiniz."},
    {"CRDSTTMP", "Geçici Kapali Kart"},
    {"CRDSTTNF", "Kart istatistikleri bulunamadi."},
    {"CRDSTTOLNF", "Kart online istatistikleri bulunamadi."},
    {"CRDTPINV", "Geçersiz Kart Türü"},
    {"CURCODENF", "Döviz kuru bulunamadi."},
    {"CURMS", "Döviz Kuru Hatasi"},
    {"CURNA", "Döviz kuru bulunamadi."},
    {"CURRTNM", "ÖKC için döviz kuru eslesmedi."},
    {"CUSACCBL", "Müsteri hesabi bloke edildi."},
    {"CUSANNCEXC", "Customer Annual Deficient payment count exceeded."},
    {"CUSDLMTEXC", "Müsteri günlük ATM nakit çekme limiti asildi."},
    {"CUSDLQERR", "Gecikmedeki Müsteri"},
    {"CUSDLYDLQ", "Günlük Gecikmedeki Müsteri"},
    {"CUSDLYDLQC", "Günlük Gecikmedeki Müsteri Nakit Avans"},
    {"CUSFLWST", "Müsteri, izleme statüsünde"},
    {"CUSINV", "Geçersiz Müsteri"},
    {"CUSLMTEXC", "Kullanilabilir müsteri limiti yetersiz."},
    {"CUSLMTUSNF", "Kullanilan müsteri limiti bulunamadi."},
    {"CUSMANF", "Müsteri, CustomerMaster tablosunda bulunamadi."},
    {"CUSMRCINF", "Is yeri numarasi bulunamadi."},
    {"CUSPERDLQ", "Periyodik Gecikmedeki Müsteri"},
    {"CUSPERDLQC", "Periyodik Gecikmedeki Müsteri Nakit Avans"},
    {"CUSPMTCEXC", "Customer Deficient payment count exceeded."},
    {"CUSSTTNA", "Müsteri statü koduna izin verilmedi."},
    {"CVV2BYPNP", "CVV2 siz isleme, terminal tarafindan izin verilmedi."},
    {"CVV2FA", "CVV2 Dogrulama Hatasi"},
    {"CVV2RTCEXC", "CVV2 deneme sayaci asildi."},
    {"CVVFA", "CVV Dogrulama Hatasi"},
    {"CVVMS", "CVV Hatasi"},
    {"DCVVFA", "DCVV Dogrulama Hatasi"},
    {"DCVVNA", "dCvv kontrolüne izin verilmedi."},
    {"DLYAMTLMT", "Günlük tutar limiti asildi."},
    {"DLYCNTLMT", "Günlük adet limiti asildi."},
    {"DMCRDMCNA", "Domestic kartlar ile döviz işlem yapılamaz"},
    {"DMCRDTXNNA", "Domestic Kredi Karti islemine izin verilmedi."},
    {"DMDBTTXNNA", "Domestic Debit Kart islemine izin verilmedi."},
    {"DUPLREQ", "Tekrarli Talep"},
    {"DUPLREQUTD", "Ayni Utid ile tekrarli talep"},
    {"ECOMFSWCAV", "CAVV datasi olmadan e-ticaret islem denemesi"},
    {"ECOMWCAVV", "Kart dogrulama kodu olmadan e-ticaret islem denemesi"},
    {"ECOMWDATA", "E-ticaret islem datasi olmadan islem denemesi"},
    {"EINSCLCERR", "Taksit Hesaplama Hatasi"},
    {"EINSCNTERR", "Taksit Sayisi Hatasi"},
    {"EINSCOMCNA", "Taksite izin verilmedi."},
    {"EINSNP", "Taksite izin verilmedi."},
    {"EINSWBNTNA", "Taksit Hesaplama Hatasi"},
    {"EMBBL", "Basim Blokeli Kart"},
    {"EMPPRM", "Bos Parametre"},
    {"ENDLMEXC", "Ciro limiti aşıldı"},
    {"ERROR", "Genel Hata"},
    {"EXDTMSTINV", "Geçersiz Son Kullanim Tarihi"},
    {"EXDTRQINV", "Geçersiz Son Kullanim Tarihi"},
    {"EXPDTMM", "Son Kullanim Tarihi eslesmedi."},
    {"EXPDTMS", "Vade Tarihi Hatasi"},
    {"FB_ACCNV", "Hesap kapalı durumda"},
    {"FB_BLNKMH", "Hesap bakiyesi yetersiz, KMH Hesabından kullanılabilir"},
    {"FB_CRDAMNT", "Herhangi bir kredi bulunamadı"},
    {"FB_CUSTNTF", "Müşteri bilgileri bulunamadı"},
    {"FB_INVOTP", "OTP gecersiz"},
    {"FB_LMTDACC", "Hesapta kısıt var"},
    {"FB_NFOTP", "OTP kaydi bulunamadi"},
    {"FBENTNA", "Fallback isleme izin verilmedi."},
    {"FBTXAMTEXC", "Fallback islem tutari asildi."},
    {"FBTXCNTEXC", "Fallback islem adedi asildi."},
    {"FEEPRFLNF", "Komisyon profili bulunamadı."},
    {"FINSAMTNE", "FlexInstall Amount Is Not Equal Amount"},
    {"FINSCNTNE", "FlexInstall Count Is Not Equal Install Count"},
    {"FINSDATMS", "Flex Install Data Required"},
    {"FRBDNCNTRY", "Yasaklı ülke kartı"},
    {"FRDCRDNA", "Fraud Kart"},
    {"FRDCTLFA", "Fraud ? Geçersiz Islem"},
    {"FRMRULEINV", "Geçersiz Kural"},
    {"HLFSECINV", "Half Secure İşlem Hatası"},
    {"HSMCOMERR", "Communication error with the KMT when generating TPK!"},
    {"HSMSCHINV", "Geçersiz Kart Semasi"},
    {"ICCMS", "ICC Data Hatasi"},
    {"ICVVFA", "ICVV Dogrulama Hatasi"},
    {"IICDETNF", "Kart ICC detayi bulunamadi."},
    {"IINTCLCERR", "Taksit Hesaplama Hatasi"},
    {"INQTXNA", "Sorgu islemine izin verilmedi."},
    {"INSCNTINV", "Geçersiz Taksit Sayisi"},
    {"INSCNTMS", "Taksit Sayisi Hatasi"},
    {"INSFPYMERR", "Ödeme Hatasi"},
    {"INSTBINNC", "BIN, taksitli isleme kapalidir."},
    {"INSTCNTERR", "Terminal Kart Taksit Limiti Hatasi"},
    {"INSTXMCCNA", "MCC için taksite izin verilmedi."},
    {"INSTXNA", "Taksite izin verilmedi."},
    {"INSTXNNA", "Geçersiz Taksit Islemi"},
    {"INTCADVCNA", "Uluslararasi nakit çekim islemine izin verilmedi."},
    {"INTCADVPNA", "Uluslararasi nakit çekim islemine izin verilmedi."},
    {"INTTXNNA", "Uluslararasi isleme izin verilmedi."},
    {"ITXMRCRL", "Kisitli ürün için is yeri iliskisi bulunamadi."},
    {"ITXRAGRCA", "Tohum Kart Islem Kisiti"},
    {"KYPRFNF", "Key profil detayi bulunamadi."},
    {"LCLCURNF", "Yerel döviz kodu bulunamadi."},
    {"LGLLMTEXC", "Yasal limit asildi."},
    {"LGLRTNF", "Yasal oranlar bulunamadi."},
    {"LMTAMTEXC", "Kart limiti yetersiz"},
    {"LMTCNTEXC", "Limit asildi."},
    {"LMTPRFNF", "Kart Limit Profili bulunamadi."},
    {"LMTUPDERR", "Limit Güncelleme Hatasi"},
    {"LOUGMRCINV", "Lounge Kontrolü: Geçersiz Is Yeri"},
    {"LOUGMRCST", "Lounge Kontrolü: Is yeri aktif degil."},
    {"LSTCRD", "Kayip Kart"},
    {"MAGENTNA", "Manyetik girise izin verilmedi."},
    {"MANENTNA", "Manuel girise izin verilmedi."},
    {"MCCGRLEINV", "Geçersiz MCG Kurali"},
    {"MCCGRMS", "Is yeri grup kodu hatasi"},
    {"MCCINV", "Geçersiz MCC"},
    {"MCCNF", "MCC bulunamadi."},
    {"MCCRLEINV", "Geçersiz MCC Kurali"},
    {"MCCRSTRCTD", "Kisitli MCC"},
    {"MCRDLMTNF", "Asil kart limiti bulunamadi."},
    {"MCRDLMTUNF", "Asil kart kullanilan limiti bulunamadi."},
    {"MCRDREFNF", "Asil kart referans numarasi hatasi"},
    {"MINCTXAMT", "Min. nakit islem tutarina ulasilamadi."},
    {"MINETXAMT", "Min. express islem tutarina ulasilamadi."},
    {"MINTXAMT", "Min. islem tutarina ulasilamadi."},
    {"MLTCURNA", "Çoklu para birimine izin verilmedi."},
    {"MLYAMTLMT", "Aylik tutar limiti asildi."},
    {"MLYCNTLMT", "Aylik adet limiti asildi."},
    {"MOTOKENTAW", "Mail Order için sadece key girisine izin verilmektedir."},
    {"MRCACCINV", "Geçersiz Is Yeri Hesabi"},
    {"MRCACCNF", "Is yeri hesabi bulunamadi."},
    {"MRCACCPRNF", "Is yeri hesabi, uygun hesap degildir."},
    {"MRCADRNF", "Is yeri adresi bulunamadi."},
    {"MRCAMXNP", "Is yeri Amex iznine sahip degildir."},
    {"MRCCHQCNT", "Is yeri max çek sayisi asildi."},
    {"MRCCRDCUS", "Isyeri ve Kart Müsterisi ayni"},
    {"MRCDLRCDNF", "Is yeri bayi kodu bulunamadi."},
    {"MRCINSCNT", "Geçersiz Is Yeri Taksit Sayisi"},
    {"MRCINSNF", "Is yeri taksiti bulunamadi."},
    {"MRCINSNP", "Is yeri taksit iznine sahip degildir."},
    {"MRCINV", "Geçersiz Is Yeri"},
    {"MRCLYLINV", "Geçersiz Is Yeri Sadakat Uygulamasi"},
    {"MRCLYLNF", "Is yeri sadakat programi bulunamadi."},
    {"MRCMCCSWMS", "Is yeri gölge MCC ye sahip olmalidir."},
    {"MRCNOINV", "Geçersiz Is Yeri Numarasi"},
    {"MRCPRDRFNF", "Is yeri ürün profil detayi bulunamadi."},
    {"MRCPRDTXNP", "Is yeri islem iznine sahip degildir."},
    {"MRCPRFAINV", "Geçersiz btt profil kodu"},
    {"MRCPRFASNF", "Is yeri profili bulunamadi."},
    {"MRCSTINV", "Is yeri aktif degil."},
    {"MRCTMPCDNF", "Is yeri taslak kodu bulunamadi."},
    {"NCSHCRDNA", "Nakit olmayan isleme izin verilmedi."},
    {"NINSCNTINV", "Geçersiz Taksit Sayisi"},
    {"NINSINV", "Taksite izin verilmedi."},
    {"NOCVMLIMIT", "No CVM Tek Seferde İşlem Limiti Aşıldı"},
    {"NONSECINV", "NON SECURE ISLEME IZIN YOK"},
    {"NPRDCRDNA", "Isleme izin verilmedi."},
    {"NWPBMS", "Yeni PINBlock Hatasi"},
    {"OFFDECLN", "Islem offline reddedildi."},
    {"OLMT1TXNNA", "Kartin ilk isleminde limit asimina izin verilmemektedir."},
    {"OLMTBNTNA", "Limit asimina izin verilmemektedir."},
    {"OLMTBUSCNA", "Tüzel Kartlarda limit asimina izin verilmemektedir."},
    {"OLMTCNTEXC", "{0} Limit Exceeded. Overlimit count exceeded. UsedAmount:{1}, AvailableAmount:{2}, OverlimitCounter:{3}"},
    {"OLMTCUSNA", "Müsterinin limit asim izni bulunmamaktadir."},
    {"OLMTDCMPNA", "Kampanya isleminde limit asimina izin verilmemektedir."},
    {"OLMTINSTNA", "Taksit isleminde limit asimina izin verilmemektedir."},
    {"ONCRDTXNNA", "Onus kredi kart islemine izin verilmemektedir."},
    {"ONDBTTXNNA", "Onus debit kart islemine izin verilmemektedir."},
    {"ORGALRVR", "Orijinal islem reverse zaten yapildi."},
    {"ORGALVOID", "Orijinal islem reverse geçersiz."},
    {"ORGAMTMM", "Orijinal ve iptal islem tutari eslesmedi."},
    {"ORGDATMS", "Geçersiz Reversal: Orijinal data bos olmamalidir."},
    {"ORGNAPRV", "Orijinal onaylanmadi."},
    {"ORGNFTXNNF", "Orijinal finansal olmayan islem bulunamadi."},
    {"ORGPREANF", "Orijinal ön otorizasyon bulunamadi."},
    {"ORGRWAMTMM", "Orijinal ve iptal ödül tutari eslesmedi."},
    {"ORGTXNNF", "Orijinal bulunamadi."},
    {"PINBMS", "PIN Block Hatasi"},
    {"PINBYPNA", "PIN siz isleme izin verilmedi."},
    {"PINCHKWPIN", "PIN kontrolü"},
    {"PINFA", "PIN Dogrulama Hatasi"},
    {"PININV", "Geçersiz PIN"},
    {"PINKYTPERR", "Bilinmeyen PIN Key Tipi"},
    {"PINLMKMS", "Kart PINLMK Hatasi"},
    {"PINNA", "PIN operasyonuna izin verilmedi."},
    {"PINOPNTINV", "Geçersiz Islem Kaynagi veya PIN Belirleme Kanali"},
    {"PINPDDVCNF", "PIN Pad bulunamadi."},
    {"PINRTYEXC", "PIN deneme sayisi asildi."},
    {"PRCEDSTTNA", "Isleme izin verilmedi."},
    {"PRDBINMS", "Kart BIN eslesmedi."},
    {"PRDCLMTEXC", "Ekstre dönemindeki toplam harcama, kart limitini asti."},
    {"PRDCRD", "Taslak detayi bulunamadi."},
    {"PRDCRDERR", "Provizyon Hatasi"},
    {"PRDNF", "Ürün, CardProduct tablosunda bulunamadi."},
    {"PRDUSGAR", "Ürün Kullanim Alani Hatasi"},
    {"PREAALCLS", "Ön otorizasyon kapatilmis."},
    {"PREACLSAMT", "Ön otorizasyon kapama tutari geçersiz."},
    {"PREAEXP", "Ön otorizasyon süresi geçmis, kapatilamaz."},
    {"PREANAPRV", "Ön otorizasyona izin verilmedi."},
    {"PREANF", "Ön otorizasyon bulunamadi."},
    {"PREASTINV", "Ön otorizasyon statüsü geçersiz."},
    {"PRMLENINV", "Geçersiz Parametre Uzunlugu"},
    {"PRMOFFINV", "Geçersiz Parametre: Offset"},
    {"PRORESTAMN", "Ürün Için Alt Tutar Siniri"},
    {"PRORESTMC", "Ürün Için Kisitli MCC/MCG"},
    {"PRORESTRN", "Isleme izin verilmedi."},
    {"PRTXAMTEXC", "Islem basina tutar asildi."},
    {"PRTXLMTRTO", "Islem basina tutar limit yüzdesi asildi."},
    {"PYMFRQINV", "Geçersiz Ödeme Tutari ve Sikligi"},
    {"PYMOVRLMT", "Kredi borç ödeme limiti aşıldı"},
    {"REFAMNT", "Iade tutari, orijinal islem tutarindan fazladir."},
    {"REFAMNTMRC", "Iade tutari, is yerine izin verilen tutari asti."},
    {"REFNTALLW", "Iade islemine izin verilmedi."},
    {"RESPNOTSND", "Response gönderilmedi."},
    {"RFNDPRDNA", "Iade islemine izin verilmedi."},
    {"RRNNM", "RRN eslesmedi."},
    {"RWAMTERR", "Ödül tutari yetersizdir."},
    {"RWFGNCUR", "Yabanci para birimi ile ödül kullanimi"},
    {"RWINQRWTNA", "Ödül sorgusuna izin verilmedi."},
    {"RWMPRFNF", "Ödül çarpani profili bulunamadi."},
    {"RWOLYINSNA", "Taksitli ödül islemine izin verilmedi."},
    {"RWUPDERR", "Ödül Güncelleme Hatasi"},
    {"SBPRDINV", "Geçersiz Alt Ürün Kurali"},
    {"SBPRDNF", "Ürün, SubCardProduct tablosunda bulunamadi."},
    {"SDWCRDNOMS", "Gölge kart numarasi bulunamadi."},
    {"SMECRDERR", "Provizyon Hatasi"},
    {"SRCCHNMS", "Kaynak kanali bos olamaz."},
    {"SRCNTWMS", "Kaynak network bos olamaz."},
    {"STANERR", "Terminal Stan Hatasi"},
    {"SUBBKMIDNV", "Alt işyeri BKM ID yok"},
    {"SUBMRCADR", "Alt işyeri adresi bulunamadı"},
    {"SUBMRCCL", "Alt işyeri aktif değil"},
    {"SUBMRCNF", "Alt işyeri bulunamadı"},
    {"SUCCESSFUL", "Onaylandi"},
    {"SUPCRDSTNA", "Ek kart islemine izin verilmedi."},
    {"SYSMALFUNC", "Sistem Arızası"},
    {"TCMBRTNL", "TCMB orani yüklenemedi bugün."},
    {"TERMCLOSED", "Terminal kapalidir."},
    {"TERMDVCNF", "Terminal bulunamadi."},
    {"TERMINV", "Geçersiz Terminal"},
    {"TERMMRCERR", "Terminal is yeri hatasi"},
    {"TERMPERMNF", "Terminal izni bulunamadi."},
    {"TERMSETTNM", "Terminal ve host hash özeti eslesmedi."},
    {"TERMSNINV", "Terminal seri numarasi eslesmedi."},
    {"TERMTXLGNF", "Terminal islem logu bulunamadi."},
    {"TERMTYPINV", "Geçersiz Terminal Türü"},
    {"TOOMCHTIME", "İşlem Zaman Aşımına Uğradı"},
    {"TRCKFRMERR", "Track format hatası"},
    {"TRCKLENERR", "Track2 uzunlugu, dCVV kontrolü için yeterli degildir."},
    {"TRCKMS", "Track1/Track2 kart datasi bostur."},
    {"TRCKPRSMS", "Track1/Track2 Hatasi"},
    {"TRKSRVMM", "Track data / ürün servis kodu eslesmedi."},
    {"TRMSNINSRV", "Terminal seri numarasi sahada gözükmekte"},
    {"TRMSNNFINV", "Terminal seri numarasi POS envanterde bulunamadi."},
    {"TXNALEOD", "Islem, EOD tarafindan yapildi."},
    {"TXNALMTCH", "Islem, zaten eslestirilmisti."},
    {"TXNALNRML", "Transaction already normal"},
    {"TXNALREF", "Islem zaten iade edildi."},
    {"TXNALREV", "Islemin tersi çalistirilmisti."},
    {"TXNALVOID", "Islem geçersiz."},
    {"TXNAMTEXC", "Max. islem tutari asildi."},
    {"TXNINV", "Geçersiz Islem"},
    {"TXNSTINV", "Geçersiz Islem Statüsü"},
    {"TXSTMNPYM", "Ekstre ödenmedi."},
    {"UPMLTCURNA", "Unionpay çoklu parabirimi islemine izin verilmedi."},
    {"UPWPBNA", "UnionPay için PINBlock gerekli."},
    {"VNDRMSGNF", "Firma mesaj key bulunamadi."},
    {"VNDRPINKNF", "Firma PIN key bulunamadi."},
    {"VOIDTXALRV", "Iptalin tersi çalistirilmisti."},
    {"WEAKPIN", "Zayıf PIN"},
    {"WINTCLCERR", "Taksit Hesaplama Hatasi"},
    {"WLYAMTLMT", "Haftalik tutar limiti asildi."},
    {"WLYCNTLMT", "Haftalik adet limiti asildi."},
    {"XCTXAMTEXC", "Max. nakit islem tutari asildi."},
    {"XETXAMTEXC", "Max. express islem tutari asildi."},
    {"XMRCIDINV", "Geçersiz Amex Is Yeri ID"},
    {"YLYAMTLMT", "Yillik tutar limiti asildi."},
    {"YLYCNTLMT", "Yillik adet limiti asildi."}
};

        public static string GetResponseReasonCodeList(string code)
        {
            return ResponseReasonCodeList.TryGetValue(code, out var message) ? message : "Bilinmeyen Hata";
        }
    }

}
